"use client";

import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import { ArrowRight, BadgeCheck, BarChart3, BriefcaseBusiness, Check, Handshake, MapPin, ShieldCheck, Smartphone, WalletCards, Wrench } from "lucide-react";
import { useState } from "react";

export default function PartnerPage(){
  const [sent,setSent]=useState(false);
  return <><Navbar/><main>
    <section className="partner-hero"><div className="container partner-hero-grid"><div><span className="eyebrow"><span className="pulse"/> TurrantFix Partner Network</span><h1>Own the work.<br/><em>Grow with the network.</em></h1><p>For skilled device-repair professionals who want access to demand, a professional workflow and a reputation layer — without becoming an employee.</p><a href="#apply" className="btn btn-lime">Apply as a partner <ArrowRight/></a></div><div className="partner-hero-art"><div className="orbit"><span><Wrench/></span><span><MapPin/></span><span><WalletCards/></span><span><BadgeCheck/></span><div><Handshake/><b>Partner</b><small>Verified · Independent</small></div></div></div></div></section>

    <section className="partner-value"><div className="container"><div className="section-head center"><span className="kicker">THE MODEL</span><h2>A marketplace layer for repair professionals.</h2><p>TurrantFix is designed to coordinate demand and quality — not to turn every technician into payroll headcount.</p></div><div className="value-grid">{[[BriefcaseBusiness,"Independent operation","Partners remain independent service providers and choose eligible work within defined zones."],[BarChart3,"Demand engine","TurrantFix can route customer bookings based on skill, geography, availability and ratings."],[ShieldCheck,"Quality layer","Standard diagnostics, job evidence, customer confirmation and warranty workflows protect trust."],[WalletCards,"Transparent economics","Partner payout logic can be visible per job before acceptance, rather than negotiated after work."]].map(([I,t,d])=><div className="value-card" key={String(t)}><span><I/></span><h3>{String(t)}</h3><p>{String(d)}</p></div>)}</div></div></section>

    <section className="partner-process"><div className="container partner-process-grid"><div><span className="kicker light">PARTNER JOURNEY</span><h2>Qualification before scale.</h2><p>The operational moat is not the website. It is whether you can consistently control partner quality while expanding supply.</p></div><div>{[["01","Apply","Profile, service zone, experience and device skills."],["02","Verify","Identity, references and technical capability checks."],["03","Train","TurrantFix SOP, customer protocol and repair evidence standards."],["04","Go live","Receive eligible repair requests inside your service radius."],["05","Compound","Ratings and completion quality influence future job access."]].map(([n,t,d])=><div className="journey" key={n}><span>{n}</span><div><b>{t}</b><p>{d}</p></div></div>)}</div></div></section>

    <section className="apply" id="apply"><div className="container apply-grid"><div><span className="kicker">JOIN THE NETWORK</span><h2>Start your partner application.</h2><p>This form is frontend-only for now. Later, connect it to your database/CRM and verification workflow.</p><ul><li><Check/> Smartphone repair experience</li><li><Check/> Valid identity and address verification</li><li><Check/> Own repair toolkit</li><li><Check/> Professional customer conduct</li></ul></div>{!sent?<form onSubmit={e=>{e.preventDefault();setSent(true)}} className="partner-form"><label><span>Full name</span><input required placeholder="Your name"/></label><label><span>Mobile number</span><input required inputMode="numeric" placeholder="10-digit mobile"/></label><label><span>Primary city</span><input required placeholder="City"/></label><label><span>Years of repair experience</span><select required defaultValue=""><option value="" disabled>Select experience</option><option>Less than 1 year</option><option>1–3 years</option><option>3–5 years</option><option>5+ years</option></select></label><label className="wide"><span>Brands you repair</span><input required placeholder="Apple, Samsung, OnePlus..."/></label><button className="btn btn-dark wide">Submit application <ArrowRight/></button></form>:<div className="partner-form sent"><BadgeCheck/><h3>Application captured.</h3><p>Demo only — no data was transmitted. Connect your backend when partner operations are ready.</p></div>}</div></section>
  </main><Footer/></>
}
